name: Reconcile GitHub Issue

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - closed
      - labeled

concurrency:
  group: ${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  reconcile-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reconcile Issue
        id: create
        uses: eriknelson/github-actions/reconcile-issue@remove-watchers
        with:
          jiraBaseUrl: https://issues.redhat.com
          jiraToken: ${{ secrets.JIRA_API_TOKEN }}
          jiraProject: MTRHO
          additionalLabels: community
          addWatchers: ernelson@redhat.com
          removeWatchers: migeng-robot@redhat.com
